name: "CI"
on: push
jobs:
  translation-sync:
    name: "Translation sync check"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install gettext"
        run: |
          sudo apt-get update
          sudo apt-get install gettext

      - name: "Cache NPM dependencies"
        uses: actions/cache@v2
        env:
          cache-version: 1
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-
            npm-dependencies-${{ runner.os }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Update translations"
        run: |
          npm run update-translations

      - name: "Check for clean repo"
        run: |
          [ -z "$(git status --porcelain)" ] || (c=$?; git status; (exit $c))

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install gettext"
        run: |
          sudo apt-get update
          sudo apt-get install gettext

      - name: "Cache Composer dependencies"
        uses: actions/cache@v2
        env:
          cache-version: 1
        with:
          path: "~/.composer/cache"
          key: composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('composer.json') }}
            composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-
            composer-dependencies-${{ runner.os }}-

      - name: "Install Composer dependencies"
        run: |
          npm install -n --prefer-dist

      - name: "Cache NPM dependencies"
        uses: actions/cache@v2
        env:
          cache-version: 1
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-
            npm-dependencies-${{ runner.os }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Build"
        run: |
          npm run build
