name: "Release"
on:
  push:
    tags:
      - "*"
env:
  php-version: 8.1
  cache-version: 1
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Install gettext"
        run: |
          sudo apt-get install gettext

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php-version }}
          coverage: none

      - name: "Cache Composer dependencies"
        uses: actions/cache@v4
        with:
          path: "~/.composer/cache"
          key: composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('composer.json') }}
            composer-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install Composer dependencies"
        run: |
          composer install -n --prefer-dist

      - name: "Cache NPM dependencies"
        uses: actions/cache@v4
        with:
          path: "~/.npm"
          key: npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('package.json') }}
            npm-dependencies-${{ runner.os }}-${{ env.cache-version }}-

      - name: "Install NPM dependencies"
        run: |
          npm ci

      - name: "Build"
        env:
          NODE_ENV: 'production'
        run: |
          npm run build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "build-artifact"
          path: dist

  release:
    name: "Create a release"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Download artifact"
        uses: actions/download-artifact@v5
        with:
          name: "build-artifact"
          path: ${{ github.event.repository.name }}

      - name: Get the version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: "Create zip"
        run: |
          zip -r ${{ github.event.repository.name }}.${{ steps.version.outputs.VERSION }}.zip ${{ github.event.repository.name }}

      - name: "Extract changelog"
        run: |
          sed -n '/=\s\?${{ steps.version.outputs.VERSION }}\s\?=/{:a;n;/=.*/b;p;ba}' ${{ github.event.repository.name }}/readme.txt > body.md

      - name: "Create a release"
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Version ${{ steps.version.outputs.VERSION }}
          body_path: ./body.md
          files: ${{ github.event.repository.name }}.${{ steps.version.outputs.VERSION }}.zip
