name: "Translatin sync check"
on: push
jobs:
  translation-sync:
    name: "Translatin sync check"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install gettext"
        run: |
          sudo apt-get update
          sudo apt-get install gettext

      - name: "Install NPM dependencies"
        run: |
          npm install

      - name: "Update translations"
        run: |
          npm run update-translations

      - name: "Check for clean repo"
        run: |
          [ -z "$(git status --porcelain)" ] || (c=$?; git status; (exit $c))
